### ISSUE TITLE
one-pager: unclear bullets and commercial software

### ISSUE THREAD

**Issue by burespe1** [burespe1/FRAME#1]
- [ ] First to bullet points are unclear align them with the relevant paragraphs

- [ ] the final fourth section describes “Enterprise Architect” without making clear that’s a commercial product first, and immediaty after explaining that we have a tiered access with (1) html browsing, (2) an architect viewer, (3) (this I’m not sure we agreed on, but potentially XMI files) and (4) the need for a Sparx EA license if you really want to create your own architectures and get the most out of our blueprint architectures

**Comment by mertaksac** [comment]
the part related to the 4th paragraph is now resolved.

**Comment by burespe1** [comment]
Vincent suggestions: It seems as if I’ve been looking at an older version of the document, or there have been edits in the meantime? 
=> Anyway, these two bullets are fine!
As for your suggestion to insert commercial I’d use **“off-the-shelf”** instead, but for now that would do the trick – if you think explaining the different levels of access is too much

**Comment by mertaksac** [comment]
the questions from Vincent is now resolved.
closing this issue to have only one issue related to the leaflet
