### ISSUE TITLE
Low Level Function stereotype

### ISSUE THREAD

**Issue by mertaksac** [burespe1/FRAME#10]
The LLF in the FRAME_Toolbox is not of the same stereotype of the LLF in the Frame Next Technology / DFD Toolbox (the functions in the FRAME Repository).
Since they are of different stereotypes, they appear differently in the project browser. 

![image](https://user-images.githubusercontent.com/71774192/99525680-36c5a100-29ab-11eb-8197-9f754db13aa6.png)

![image](https://user-images.githubusercontent.com/71774192/99525701-3c22eb80-29ab-11eb-9fa6-5b4f33cd3f6d.png)

**Comment by burespe1** [comment]
discuss name of the issue (they should describe the problem)

**Comment by mertaksac** [comment]
this issue needs to be raised as suggestions for the LLF in FRAME Toolbox , (and Metamodel)

Benjamin said that we had agreed with nizam in a way that we work on developing the new FRAME and as soon as we decide how functions should be designed, he will change all functions in FRAME Repository accordingly.

Now all Functions are stereotyped as Class.. why was this decided? 
Isn't the "Process" Stereotype better for a function?
