### ISSUE TITLE
User Need stereotype

### ISSUE THREAD

**Issue by mertaksac** [burespe1/FRAME#11]
When a new user need is created from the FRAME_Toolbox, it is displayed as a Use Case on the diagram.

![image](https://user-images.githubusercontent.com/71774192/99525810-65dc1280-29ab-11eb-9f49-6bc8c5dae255.png)

**Comment by mertaksac** [comment]
Suggestion: User Needs stereotype should be based on Requirement.

![image](https://user-images.githubusercontent.com/71774192/99525875-8015f080-29ab-11eb-8e26-91884c5d4f55.png)

**Comment by burespe1** [comment]
discuss on rename and colation

**Comment by mertaksac** [comment]
this suggestion was accepted by Benjamin and it is [solved](https://github.com/FRAME-NEXT/FRAME/issues/8) in the current release of V5 DRAFT
