### ISSUE TITLE
Architecture Methodology

### ISSUE THREAD

**Issue by mertaksac** [burespe1/FRAME#12]
We need to agree on a general SOP "standard operating procedure" for users to create their own architectures using our new tool.

**Comment by mertaksac** [comment]
Suggestion: The steps to be followed should be as follows:

1 - Define Stakeholders (part of organizational view)
2 - Layout the Motivational Layer
3 - Choose User Needs
4 - Build the Functional View
5 - Define components, subsystems, modules and match with functionality
6 - Deduct the Communications view from the physical view interfaces
7 - Assign roles and complete organizational view

**Comment by mertaksac** [comment]
Suggestion: we should re run the eCall or NAP examples by keeping this sequence of events in mind, and replicate the "user experience". In the meanwhile we should re examine the artefacts, fix toolbox where necessary.

**Comment by mertaksac** [comment]
a sequence of activities to be followed which will the end result will be a fully completed reference architecture

**Comment by burespe1** [comment]
colate in one comment and create one issue out of it (may be by edditing the first issue)

**Comment by mertaksac** [comment]
This must be re-issued, maybe brokedown into smaller parts. I am now working on a "expanded skeleton metamodel" document, which will introduce rational behind working on a skeleton and then detail each artefact and connection.

The issue of having a standard way of producing a reference architecture is also being discussed under User Guide topic with Richard and Peter, I cant say we have agreement (please see the email from peter, subject FRAME User Needs, sent on 3rd of December 2020 at 17:10 CET)

I still think that we need to decide on a "formalized" (standardized) way of creating reference architectures, 

1 - As you have stated in your reply, so what is the purpose that we try to create a tool and an ITS specific architecture such as FRAME, lets delete everything and let the user create ANY architecture using Enterprise Architect?

2 - As i have stated in last WP3/4 Technical Discussion telco, it is great if we could have traceability between the system in the deployment level up until ITS Vision defined by stakeholder.. also it is not such a big dream, we saw it was possible in MoToTR training.. 

3 - Its instinctive to try to fit everything in a sequential process that is followed step by step, this way it is sane, other wise everything flies around as concepts that are not tied to ground, they easily become madness. Thats why we immediately jump in such a sequential process design to be used in the training. 

(I wrote everything above to be re-drafted)
