### ISSUE TITLE
Creating Custom Properties for specific element types (artefacts) in EA

### ISSUE THREAD

**Issue by mertaksac** [burespe1/FRAME#13]
There are tables to be filled for many artefacts described in the wiki.

Is it possible to replicate such tables in EA.

Can we do it by adding a custom section in the properties dialogue?

![Picture10](https://user-images.githubusercontent.com/71774192/99527032-34644680-29ad-11eb-877d-54d5106ed801.png)

**Comment by mertaksac** [comment]
the Toolbox will not be completed without doing this

**Comment by burespe1** [comment]
again we need to redraft this into "one comment" with more elaboration.

**Comment by mertaksac** [comment]
I agree redrafting issue with better topic, explanation and graphis. I think we first need to finalize discussions on the artefacts and the metamodel and then go in detail each one.
