### ISSUE TITLE
User Needs to Functional View

### ISSUE THREAD

**Issue by mertaksac** [burespe1/FRAME#14]
following are the steps to be followed to build the functional view.

1) 
![Picture11](https://user-images.githubusercontent.com/71774192/99527890-8bb6e680-29ae-11eb-8372-c7d8ff09a62c.png)

2)
![Picture12](https://user-images.githubusercontent.com/71774192/99527897-8f4a6d80-29ae-11eb-98bf-883d25f3e41a.png)

3)
![Picture13](https://user-images.githubusercontent.com/71774192/99527903-940f2180-29ae-11eb-9db2-1e2ce1d8862a.png)

can we automate this process within EA?

**Comment by burespe1** [comment]
this needs to separate text from the pictures and may be relate to it how the UNs are represented

**Comment by mertaksac** [comment]
I agree redrafting issue with better topic, explanation and graphis. I think we can keep this issue on hold for now, since any topic related to automation have no agenda until the coming year.
