### ISSUE TITLE
Functional View to Physical View

### ISSUE THREAD

**Issue by mertaksac** [burespe1/FRAME#15]
following are the steps to be followed to build a physical view.

1)
![Picture14](https://user-images.githubusercontent.com/71774192/99528673-b48bab80-29af-11eb-9c6f-b388fe53c8fe.png)

2)
![Picture15](https://user-images.githubusercontent.com/71774192/99528688-b81f3280-29af-11eb-9094-fb28ca1b3ed6.png)

3)
![Picture16](https://user-images.githubusercontent.com/71774192/99528699-bc4b5000-29af-11eb-807a-4908ee8164b2.png)

can we automate this process within EA?

**Comment by burespe1** [comment]
we need to work on the issue bit more, may be include some our pistures from yEd.

**Comment by mertaksac** [comment]
I agree redrafting issue with better topic, explanation and graphis. I think we can keep this issue on hold for now, since any topic related to automation have no agenda until the coming year.
