### ISSUE TITLE
Physical View to Communications View

### ISSUE THREAD

**Issue by mertaksac** [burespe1/FRAME#16]
The data flows between two subsystems will be identified with the interfaces when the physical view is completed.

What other details should be modelled in EA for the communications view?

**Comment by mertaksac** [comment]
the Communications View example from MoToTR raining

![Uploading image.png…]()

**Comment by mertaksac** [comment]
the communications view example from the MoToTR traning

![image](https://user-images.githubusercontent.com/71774192/99918686-b3e57300-2d29-11eb-977b-6a957264fcb9.png)

**Comment by burespe1** [comment]
this needs some clarification.

**Comment by mertaksac** [comment]
this is not really AN issue, this was saying that we should discuss what is in the communication view and how we should model them in EA, a very general topic.. This should be broke down other issues, after being discussed between maintainers
