### ISSUE TITLE
Laying Out Data Flows in Diagrams

### ISSUE THREAD

**Issue by mertaksac** [burespe1/FRAME#18]
Is it possible to place “data flow” elements automatically between IN and OUT connectors and place all of these (IN connector, the dataflow and the OUT connector) linearly between functions and datastores or terminators while drawing functional view diagrams? 
![image](https://user-images.githubusercontent.com/71774192/99529811-7b543b00-29b1-11eb-94ac-67cb357a7eba.png)

**Comment by burespe1** [comment]
this issue shall be connected to issue #20 and #21 = redraft, please

**Comment by mertaksac** [comment]
I agree redrafting issue with better topic, explanation and graphis. I think we can keep this issue on hold for now, since any topic related to automation have no agenda until the coming year.

**Comment by mertaksac** [comment]
Closing the issue since a more comprehensive issue related to automation needs to be redrafted, see Petr's previous comment.
