### ISSUE TITLE
Placing Functions inside Subsystems / Modules in Diagrams

### ISSUE THREAD

**Issue by mertaksac** [burespe1/FRAME#19]
After user creates components and establishes relations between components and low level functions, is it possible for EA to draw a physical view diagram placing functions to correct components / subsystems?

**Comment by burespe1** [comment]
some more explanation and may be a picture is needed. After redrafting we will create a new issue out of this

**Comment by mertaksac** [comment]
I agree redrafting issue with better topic, explanation and graphis. I think we can keep this issue on hold for now, since any topic related to automation have no agenda until the coming year.

**Comment by mertaksac** [comment]
Closing the issue since a more comprehensive issue related to automation needs to be redrafted, see Petr's previous comment.
