### ISSUE TITLE
one-pager

### ISSUE THREAD

**Issue by burespe1** [burespe1/FRAME#2]
https://github.com/burespe1/FRAME/blob/master/materials/leaflet2020.md

- [x] Minor (grammatical) – text with first picture, second sentence – “It was updated …” would be better as “It has been updated …”

- [x] More important: I note that there are two websites mentioned in the footer, with ‘architecture’ pointing to www.frame-online.eu . If I didn’t know anything better I would expect to find a new EA version of the architecture in this website, but it’s not there (at the moment). proposed change:
[here is the logo] new architecture: [frame-next.eu](frame-next.eu)
[here is the logo] old versions: [frame-online.eu](frame-online.eu)

**Comment by mertaksac** [comment]
email sent to PHJ asking his confirmation about the changes

**Comment by mertaksac** [comment]
the modifications suggested by PHJ and Vincent is now done

**Comment by mertaksac** [comment]
this was sent to maintainers.. issue will be closed a new one to be started if the topic gets active again.

**Comment by mertaksac** [comment]
the leaflet was published on frame-next.eu https://frame-next.eu/wp-content/uploads/2020/12/FRAME-NEXT-leaflet-2020.pdf
