### ISSUE TITLE
Laying out Functions in Diagrams

### ISSUE THREAD

**Issue by mertaksac** [burespe1/FRAME#20]
Is there a way to find the best position for a given function on a diagram automatically and layout them on the diagram according to dataflow connections to be established (functions exchange information are closer to each other)?

**Comment by burespe1** [comment]
this is related to issue #21 and shall be redrafted and joined togeher

**Comment by mertaksac** [comment]
this issue is directly related to the positions of the low level functions on a functional view diagram. The issue can be bundled with other issues related to automation, this one was specially for the behaviour of the LLF object.  I agree reformulate this issue in connection with other automation related issues, but I think we should keep automation related issues on hold for now.

**Comment by mertaksac** [comment]
Closing the issue since a more comprehensive issue related to automation needs to be redrafted, see Petr's previous comment.
