### ISSUE TITLE
Routing Data Flows in Diagrams

### ISSUE THREAD

**Issue by mertaksac** [burespe1/FRAME#21]
Is there a way to find the best best route for a given connector on a diagram automatically?

**Comment by mertaksac** [comment]
there is auto-route function in EA, this could be default for FRAME connectors

**Comment by burespe1** [comment]
this issue needs to be redrafted to be more explanatory. (I sugget after we redraft it here than we open new issue with redrafted content and delete / close this one)

**Comment by mertaksac** [comment]
this issue is related to automation, and might be gathered under a single issue with the other automation related issues. I agree to redraft the issue with better subject and explanation but I also think we should keep this one on hold, as we have other issues more relevant to discussions with maintainers

**Comment by mertaksac** [comment]
Closing the issue since a more comprehensive issue related to automation needs to be redrafted, see Petr's previous comment.
