### ISSUE TITLE
Transfer Building Blocks to EA

### ISSUE THREAD

**Issue by mertaksac** [burespe1/FRAME#23]
The building blocks, which is the NEW ENTRY POINT to architecture in our new tool and make up he motivational layer should be replicated in EA.

**Comment by mertaksac** [comment]
We might need to create custom properties to be able to accommodate the empty tables in the wiki

**Comment by burespe1** [comment]
We need to discuss this, I do not understand the extent of the issue.

**Comment by mertaksac** [comment]
the building blocks from the wiki are motivational layer artefacts namely vision, mission, service description etc.
I propose we breakdown this issue in to smaller parts and deal with each building block one by one

**Comment by mertaksac** [comment]
this issue was started within the "skeleton metamodel" issue in the master repository.
https://github.com/FRAME-NEXT/FRAME/issues/13
some other artefacts such as business expectations and architecture results should be added, but these artefacts were not discussed to completion with the maintainers, so I am guessing those other artefacts will be added / placed / discussed in the following year.
