### ISSUE TITLE
Clean up WP5 folders

### ISSUE THREAD

**Issue by burespe1** [burespe1/FRAME#29]
there is a lot of stuff in [WP 5 folder](https://drive.google.com/drive/u/0/folders/1E-1J9mO3JOuj5otTXgblwiUoCNBJYvJq) some of it unnecessary - clen it up. (discuss sharing with Petr)

**Comment by mertaksac** [comment]
The Cleanup is completed.

New Folder "From Mert" is created in the shared [google drive](https://drive.google.com/drive/folders/1E-1J9mO3JOuj5otTXgblwiUoCNBJYvJq?usp=sharing).

Find the clean WP5 folder [here](https://drive.google.com/drive/folders/1pEM9Iyxufdju4Y0j6ljvTz_R8dH89osz?usp=sharing).

This issue will be moved to "Done" column and will be closed.
