### ISSUE TITLE
WP5 Status Quo Report

### ISSUE THREAD

**Issue by mertaksac** [burespe1/FRAME#30]
Study what has been done before and make a report

**Comment by mertaksac** [comment]
started here: https://docs.google.com/presentation/d/1b2G2kUt7m3M28Mm0AuIBoVibVrcS5t98QTepZXjHGZ8/

will make a better report while reading individual interviews

**Comment by mertaksac** [comment]
The [Status Quo Report](https://docs.google.com/document/d/1pn1ZCLLsOi2_ehil2yLB1PpIWFksMtO0DWFNu9GGbJU) is now ready to be reviewed.

**Key Insights:**

There were many valuable points raised by the interviewee's: _(such as but not limited to)_
- The user needs / functional view is too much detailed, need a summary for the decision makers
- The user needs / functional view is too much focused on central players such as National Traffic Management Organizations, Public Transportation Authorities etc but is not oriented to end users (travelers)
- Communication Standards should be addressed, included
- Premade service templates (similar to Arc-it) including their physical / organizational / enterprise views etc

were these points addressed?

We have to be able to address these issues and be able to defend ourselves.
If we have a solution we should declare it or if it will not be solved we simply should tell why.

We need to be able to fix the points that were raised by interviewees and at the end of the project we have to be able to "convince" them that FRAME is actually will be useful for them (20 years of development is not just a pointless effort but actually aligned with the industry - if not superior).

**What I want to do next:**

- [ ] 1. Go over the interviews with Richard, find answers to existing problems, create solution / defense for un addressed issues

People especially who made these interviews (maintainers) know there are some infeasible aspects found in FRAME and the intended people do not want to use FRAME (at least until these points are improved)

and since these bleeding issues not solved, or even mentioned most of the maintainers stopped working for the project

- [ ] 2. Touch maintainer members from inside. They have great insight but somehow seem to stop working for the project.

Re ask their opinions on what to do next (be it re thinking how the user needs are formalized, developing new architecture methodologies and how we do things in EA) and restart discussions around some points, follow up these issues with all parties (but individually) until they are fixed.

Many things are beyond the project lifespan (6 months) and this is actually work done for "maintenance" or the next FRAME NEXT project. I know this fact. so please curb my enthusiasm and lets find the most realistic one.

- [ ] 3. Make very frequent telcos with everyone, (vincent willi holger richard, austriatech)

There is problem in maintainers telcos. nothing is being seriously discussed / addressed, or things move VERY slow. to break this, the telcos should be done with individuals, one to one basis.

- [ ] 4. Aid austriatech in making technical changes

I learned how to make bulk changes in the current Repository and i am willing to learn more about using EA.
I want to establish better contact with Benjamin and help him modifying the model. With no/little help from Sparx this could be an acceleration point.

**Comment by burespe1** [comment]
issue for "how we addressed the stakeholders concerns" from bullet point 1. make bullet points checkable, and check them when we have the issue concerning the bullet created

**Comment by mertaksac** [comment]
it is called task list

- [ ]  on 
- [ ] two
- [ ] three

**Comment by mertaksac** [comment]
This issue was discussed in daily telco on 09.02.2021.

Two new issues arose from this issue:

1) update table of interviews and add identifier
2) insights form old interviews document

This issue will be moved to "Done" column and will be closed.
