### ISSUE TITLE
Use of Frame Repository in FRAME_NEXT (Compatibility)

### ISSUE THREAD

**Issue by mertaksac** [burespe1/FRAME#9]
While we were working on MoToTR training .eapx files, we saw that a model package that was created in the version that was published in frame-next.eu was not compatible with "FrameNext - 2020.09.23.eapx" where Richard make the updates on the Frame Repository.

We exported our diagrams that we have created in the "DRAFTVERSION.eapx" but when we imported them in  "FrameNext - 2020.09.23.eapx" the diagrams appeared to be blank.

That was because the GUIDs of used elements did not match.

This shouldn't happen.

We have to base everything else we produce on the Frame Repository which first was created by SPARX and then constantly updated by Richard.

Anytime we create any packages and import it into the base Frame Repository, the GUID should match.

and also Richard should make all changes on the base version of the repository and thus any time he makes updates we should be able to import those changes on the current version that is published on the website.

**Comment by burespe1** [comment]
redraft name of the issue

**Comment by mertaksac** [comment]
I need to re-test this. If problem still persist I will re-draft using the latest version in the website.. This might be a problem benjamin solved in earlier versions
